version: '3.8'

services:
  analyzer:
    build: .
    container_name: cake_analyzer
    volumes:
      # Ваша текущая папка с системой промптов
      - .:/app
      # МОНТИРУЕМ РЕАЛЬНЫЙ ПРОЕКТ:
      # Внутри контейнера он будет доступен по пути /projects/sic
      - ../sic:/sic
    working_dir: /app